receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  coralogix:
    private_key: "cxtp_KCHP1xzNY6FDpQVLQ84c8KycY6JvX3"
    application_name: "otel-demo"
    subsystem_name: "otel-demo-subsystem"
    domain: "api.cx498.coralogix.com"
    timeout: 30s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [coralogix]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [coralogix]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [coralogix]
